const DB_NAME='expedientes_medicos_v1';
const DB_VERSION=1;
const STORE_PATIENTS='patients', STORE_VISITS='visits', STORE_PAYMENTS='payments', STORE_FILES='files';
let db=null, currentPatientId=null;
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(n||0));
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}_${Math.random().toString(16).slice(2)}`;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const d=req.result;if(!d.objectStoreNames.contains(STORE_PATIENTS)){const s=d.createObjectStore(STORE_PATIENTS,{keyPath:'id'});s.createIndex('name','fullNameLower',{unique:false});s.createIndex('updatedAt','updatedAt',{unique:false});}
if(!d.objectStoreNames.contains(STORE_VISITS)){const s=d.createObjectStore(STORE_VISITS,{keyPath:'id'});s.createIndex('patientId','patientId',{unique:false});s.createIndex('date','date',{unique:false});}
if(!d.objectStoreNames.contains(STORE_PAYMENTS)){const s=d.createObjectStore(STORE_PAYMENTS,{keyPath:'id'});s.createIndex('patientId','patientId',{unique:false});s.createIndex('date','date',{unique:false});}
if(!d.objectStoreNames.contains(STORE_FILES)){const s=d.createObjectStore(STORE_FILES,{keyPath:'id'});s.createIndex('patientId','patientId',{unique:false});s.createIndex('createdAt','createdAt',{unique:false});}};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});}
function tx(store,mode='readonly'){return db.transaction(store,mode).objectStore(store)}
function getAll(store){return new Promise((resolve,reject)=>{const r=tx(store).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function getOne(store,id){return new Promise((resolve,reject)=>{const r=tx(store).get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function putOne(store,obj){return new Promise((resolve,reject)=>{const r=tx(store,'readwrite').put(obj);r.onsuccess=()=>resolve(obj);r.onerror=()=>reject(r.error)})}
function deleteOne(store,id){return new Promise((resolve,reject)=>{const r=tx(store,'readwrite').delete(id);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})}
function byPatient(store,patientId){return new Promise((resolve,reject)=>{const idx=tx(store).index('patientId'),r=idx.getAll(IDBKeyRange.only(patientId));r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function clearStore(store){return new Promise((resolve,reject)=>{const r=tx(store,'readwrite').clear();r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),2200)}
function showView(id){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+id).classList.add('active');$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='patientsView'){currentPatientId=null;renderPatients();$('#pageTitle').textContent='Pacientes';$('#pageSubtitle').textContent='Organiza pacientes, consultas, archivos y pagos.';$('#addPatientTop').classList.remove('hidden')}else if(id==='settingsView'){currentPatientId=null;$('#pageTitle').textContent='Ajustes';$('#pageSubtitle').textContent='Respaldo y almacenamiento.';$('#addPatientTop').classList.add('hidden')}}
async function financialFor(patient){const payments=await byPatient(STORE_PAYMENTS,patient.id);const paid=payments.reduce((a,b)=>a+Number(b.amount||0),0), total=Number(patient.treatmentTotal||0), balance=Math.max(total-paid,0);return{paid,total,balance,payments}}
async function renderPatients(){const list=$('#patientList'), empty=$('#emptyPatients');let patients=await getAll(STORE_PATIENTS);patients.sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||''));const q=$('#patientSearch').value.trim().toLowerCase(),filter=$('#balanceFilter').value;let totalPending=0,totalPaid=0;const enriched=[];for(const p of patients){const f=await financialFor(p);totalPending+=f.balance;totalPaid+=f.paid;enriched.push({p,f})}
$('#totalPatients').textContent=patients.length;$('#totalPending').textContent=money(totalPending);$('#totalPaid').textContent=money(totalPaid);
const rows=enriched.filter(({p,f})=>{const match=!q||p.fullNameLower.includes(q)||(p.diagnosis||'').toLowerCase().includes(q);const fm=filter==='all'||(filter==='pending'&&f.balance>0.009)||(filter==='paid'&&f.balance<=0.009);return match&&fm});
list.innerHTML=rows.map(({p,f})=>`<article class="patient-card" data-id="${p.id}"><div class="patient-row"><div><div class="patient-name">${esc(p.fullName)}</div><div class="patient-dx">${esc(p.diagnosis||'Sin diagnóstico registrado')}</div></div><span class="balance-pill ${f.balance>0.009?'pending':'paid'}">${f.balance>0.009?'Saldo '+money(f.balance):'Liquidado'}</span></div><div class="patient-meta"><span>📅 ${esc(p.birthDate||'Sin fecha')}</span><span>📞 ${esc(p.phone||'Sin teléfono')}</span><span>💳 Abonado ${money(f.paid)}</span></div></article>`).join('');
empty.classList.toggle('hidden',patients.length!==0);list.classList.toggle('hidden',patients.length===0);$$('.patient-card').forEach(c=>c.onclick=()=>openPatient(c.dataset.id));}
async function openPatient(id){currentPatientId=id;const p=await getOne(STORE_PATIENTS,id);if(!p)return;const f=await financialFor(p),visits=(await byPatient(STORE_VISITS,id)).sort((a,b)=>b.date.localeCompare(a.date)),files=(await byPatient(STORE_FILES,id)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
showPatientShell(p);const html=`<div class="detail-hero"><div class="hero-top"><div><div class="eyebrow" style="color:#bff4ea">EXPEDIENTE</div><h2>${esc(p.fullName)}</h2><div class="muted">${esc(p.birthDate||'Sin fecha de nacimiento')} · ${esc(p.phone||'Sin teléfono')}</div></div><div class="hero-actions"><button id="editPatient">Editar</button><button id="printPatient">PDF</button></div></div><p class="hero-dx"><strong>Diagnóstico:</strong> ${esc(p.diagnosis||'Sin diagnóstico registrado')}</p>${p.generalNotes?`<p class="hero-dx"><strong>Notas:</strong> ${esc(p.generalNotes)}</p>`:''}<div class="finance-grid"><div class="finance-box"><span>Total</span><strong>${money(f.total)}</strong></div><div class="finance-box"><span>Abonado</span><strong>${money(f.paid)}</strong></div><div class="finance-box"><span>Saldo</span><strong>${money(f.balance)}</strong></div></div></div>
<div class="detail-actions"><button class="primary-btn" id="addVisit">＋ Registrar consulta</button><button class="secondary-btn" id="addPayment">＋ Registrar abono</button><button class="secondary-btn" id="addFile">＋ Subir archivo</button></div>
<section class="section-card"><div class="section-head"><div><div class="eyebrow">EVOLUCIÓN</div><h3>Consultas y progreso</h3></div><span class="muted">${visits.length}</span></div><div class="timeline">${visits.length?visits.map(v=>`<div class="timeline-item"><strong>${esc(v.date)}${v.reason?' · '+esc(v.reason):''}</strong><p>${esc(v.progress)}</p>${v.plan?`<p class="muted"><b>Indicaciones:</b> ${esc(v.plan)}</p>`:''}<button class="text-btn danger delete-visit" data-id="${v.id}">Eliminar</button></div>`).join(''):'<p class="muted">Aún no hay consultas registradas.</p>'}</div></section>
<section class="section-card"><div class="section-head"><div><div class="eyebrow">PAGOS</div><h3>Abonos</h3></div><span class="muted">${f.payments.length}</span></div>${f.payments.length?f.payments.sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<div class="payment-row"><div><strong>${money(x.amount)}</strong><small>${esc(x.date)} · ${esc(x.concept||'Abono')}</small></div><button class="text-btn danger delete-payment" data-id="${x.id}">Eliminar</button></div>`).join(''):'<p class="muted">No hay abonos registrados.</p>'}</section>
<section class="section-card"><div class="section-head"><div><div class="eyebrow">ARCHIVOS</div><h3>Imágenes y documentos</h3></div><span class="muted">${files.length}</span></div>${files.length?files.map(fileRowHtml).join(''):'<p class="muted">No hay archivos adjuntos.</p>'}</section>`;
$('#patientDetail').innerHTML=html;bindPatientDetail(p,files);}
function showPatientShell(p){$$('.view').forEach(v=>v.classList.remove('active'));$('#patientView').classList.add('active');$$('.nav-btn').forEach(b=>b.classList.remove('active'));$('#pageTitle').textContent=p.fullName;$('#pageSubtitle').textContent='Expediente del paciente';$('#addPatientTop').classList.add('hidden')}
function fileRowHtml(f){const isImg=(f.type||'').startsWith('image/');return `<div class="file-row"><div class="file-main">${isImg?`<img class="file-thumb" src="${URL.createObjectURL(f.blob)}" alt="">`:`<div class="file-thumb file-icon">📄</div>`}<div style="min-width:0"><div class="file-name">${esc(f.name)}</div><small>${esc(f.description||f.type||'Archivo')} · ${new Date(f.createdAt).toLocaleDateString('es-MX')}</small></div></div><div class="file-actions"><button class="open-file" data-id="${f.id}">Ver</button><button class="delete-file" data-id="${f.id}">✕</button></div></div>`}
function bindPatientDetail(p,files){$('#editPatient').onclick=()=>openPatientDialog(p);$('#printPatient').onclick=()=>window.print();$('#addVisit').onclick=()=>{$('#visitForm').reset();$('#visitDate').value=today();$('#visitDialog').showModal()};$('#addPayment').onclick=()=>{$('#paymentForm').reset();$('#paymentDate').value=today();$('#paymentDialog').showModal()};$('#addFile').onclick=()=>{$('#fileForm').reset();$('#fileDialog').showModal()};
$$('.delete-visit').forEach(b=>b.onclick=async()=>{if(confirm('¿Eliminar esta consulta?')){await deleteOne(STORE_VISITS,b.dataset.id);await openPatient(currentPatientId)}});$$('.delete-payment').forEach(b=>b.onclick=async()=>{if(confirm('¿Eliminar este abono?')){await deleteOne(STORE_PAYMENTS,b.dataset.id);await openPatient(currentPatientId)}});$$('.delete-file').forEach(b=>b.onclick=async()=>{if(confirm('¿Eliminar este archivo?')){await deleteOne(STORE_FILES,b.dataset.id);await openPatient(currentPatientId)}});$$('.open-file').forEach(b=>b.onclick=async()=>{const f=await getOne(STORE_FILES,b.dataset.id);const u=URL.createObjectURL(f.blob);window.open(u,'_blank');setTimeout(()=>URL.revokeObjectURL(u),60000)});}
function openPatientDialog(p=null){$('#patientForm').reset();$('#patientDialogTitle').textContent=p?'Editar paciente':'Nuevo paciente';$('#patientId').value=p?.id||'';$('#fullName').value=p?.fullName||'';$('#birthDate').value=p?.birthDate||'';$('#phone').value=p?.phone||'';$('#diagnosis').value=p?.diagnosis||'';$('#generalNotes').value=p?.generalNotes||'';$('#treatmentTotal').value=p?.treatmentTotal??0;$('#patientDialog').showModal()}
$('#patientForm').onsubmit=async e=>{e.preventDefault();const id=$('#patientId').value||uid(),old=await getOne(STORE_PATIENTS,id);const p={id,fullName:$('#fullName').value.trim(),fullNameLower:$('#fullName').value.trim().toLowerCase(),birthDate:$('#birthDate').value,phone:$('#phone').value.trim(),diagnosis:$('#diagnosis').value.trim(),generalNotes:$('#generalNotes').value.trim(),treatmentTotal:Number($('#treatmentTotal').value||0),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(!p.fullName)return;await putOne(STORE_PATIENTS,p);$('#patientDialog').close();toast('Paciente guardado');if(currentPatientId)openPatient(id);else renderPatients()};
$('#visitForm').onsubmit=async e=>{e.preventDefault();await putOne(STORE_VISITS,{id:uid(),patientId:currentPatientId,date:$('#visitDate').value,reason:$('#visitReason').value.trim(),progress:$('#visitProgress').value.trim(),plan:$('#visitPlan').value.trim(),createdAt:new Date().toISOString()});$('#visitDialog').close();await touchPatient(currentPatientId);toast('Consulta registrada');openPatient(currentPatientId)};
$('#paymentForm').onsubmit=async e=>{e.preventDefault();await putOne(STORE_PAYMENTS,{id:uid(),patientId:currentPatientId,date:$('#paymentDate').value,amount:Number($('#paymentAmount').value||0),concept:$('#paymentConcept').value.trim(),createdAt:new Date().toISOString()});$('#paymentDialog').close();await touchPatient(currentPatientId);toast('Abono registrado');openPatient(currentPatientId)};
$('#fileForm').onsubmit=async e=>{e.preventDefault();const file=$('#patientFile').files[0];if(!file)return;await putOne(STORE_FILES,{id:uid(),patientId:currentPatientId,name:file.name,type:file.type,size:file.size,description:$('#fileDescription').value.trim(),blob:file,createdAt:new Date().toISOString()});$('#fileDialog').close();await touchPatient(currentPatientId);toast('Archivo guardado');openPatient(currentPatientId)};
async function touchPatient(id){const p=await getOne(STORE_PATIENTS,id);if(p){p.updatedAt=new Date().toISOString();await putOne(STORE_PATIENTS,p)}}
$$('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());
$('#addPatientTop').onclick=()=>openPatientDialog();$('#emptyAddPatient').onclick=()=>openPatientDialog();$('#backToPatients').onclick=()=>showView('patientsView');$('#patientSearch').oninput=renderPatients;$('#balanceFilter').onchange=renderPatients;$$('.nav-btn').forEach(b=>b.onclick=()=>showView(b.dataset.view));
$('#exportBackup').onclick=async()=>{const data={version:1,exportedAt:new Date().toISOString(),patients:await getAll(STORE_PATIENTS),visits:await getAll(STORE_VISITS),payments:await getAll(STORE_PAYMENTS)};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`expedientes_respaldo_${today()}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#importBackup').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());if(!Array.isArray(data.patients))throw new Error();if(!confirm('Esto agregará/actualizará los registros del respaldo. ¿Continuar?'))return;for(const p of data.patients||[])await putOne(STORE_PATIENTS,p);for(const v of data.visits||[])await putOne(STORE_VISITS,v);for(const p of data.payments||[])await putOne(STORE_PAYMENTS,p);toast('Respaldo importado');renderPatients()}catch{alert('El archivo no parece ser un respaldo válido.')}e.target.value=''};
$('#clearAll').onclick=async()=>{if(!confirm('¿Borrar TODOS los pacientes, consultas, pagos y archivos de este dispositivo?'))return;if(!confirm('Esta acción no se puede deshacer. ¿Continuar?'))return;await Promise.all([clearStore(STORE_PATIENTS),clearStore(STORE_VISITS),clearStore(STORE_PAYMENTS),clearStore(STORE_FILES)]);toast('Datos eliminados');showView('patientsView')};
$('#loadDemo').onclick=async()=>{const existing=await getAll(STORE_PATIENTS);if(existing.length&&!confirm('Ya tienes datos. Los ejemplos se agregarán sin borrar lo existente. ¿Continuar?'))return;const p1={id:uid(),fullName:'María González López',fullNameLower:'maría gonzález lópez',birthDate:'1984-03-12',phone:'33 1234 5678',diagnosis:'Seguimiento de hipertensión arterial',generalNotes:'Paciente de ejemplo. No contiene información clínica real.',treatmentTotal:3500,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()},p2={id:uid(),fullName:'Carlos Ramírez Torres',fullNameLower:'carlos ramírez torres',birthDate:'1976-08-24',phone:'33 9876 5432',diagnosis:'Control metabólico',generalNotes:'Paciente de demostración.',treatmentTotal:2200,createdAt:new Date().toISOString(),updatedAt:new Date(Date.now()-86400000).toISOString()};await putOne(STORE_PATIENTS,p1);await putOne(STORE_PATIENTS,p2);await putOne(STORE_VISITS,{id:uid(),patientId:p1.id,date:today(),reason:'Consulta de seguimiento',progress:'Refiere mejoría general. Registro de ejemplo para visualizar la línea de tiempo.',plan:'Continuar seguimiento según criterio médico.',createdAt:new Date().toISOString()});await putOne(STORE_PAYMENTS,{id:uid(),patientId:p1.id,date:today(),amount:1500,concept:'Anticipo',createdAt:new Date().toISOString()});await putOne(STORE_PAYMENTS,{id:uid(),patientId:p2.id,date:today(),amount:2200,concept:'Liquidación',createdAt:new Date().toISOString()});toast('Datos de ejemplo cargados');showView('patientsView')};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
(async()=>{db=await openDB();$('#visitDate').value=today();$('#paymentDate').value=today();renderPatients()})();
